# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20161010_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='user',
            new_name='owner',
        ),
    ]
